"""Add source_type and article_evaluations

Revision ID: 0f7b0c14a4ad
Revises: dce66759a153
Create Date: 2026-05-08 10:18:15.206692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f7b0c14a4ad'
down_revision: Union[str, Sequence[str], None] = 'dce66759a153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('llm_label', sa.String(length=50), nullable=True),
    sa.Column('human_label', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article_identity.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_evaluations_article_id'), 'article_evaluations', ['article_id'], unique=True)
    op.create_index(op.f('ix_article_evaluations_id'), 'article_evaluations', ['id'], unique=False)
    op.add_column('rss_sources', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.drop_column('scheduler_config', 'is_scanning')
    op.drop_column('scheduler_config', 'last_scan_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_config', sa.Column('last_scan_duration', mysql.FLOAT(), nullable=True))
    op.add_column('scheduler_config', sa.Column('is_scanning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('rss_sources', 'source_type')
    op.drop_index(op.f('ix_article_evaluations_id'), table_name='article_evaluations')
    op.drop_index(op.f('ix_article_evaluations_article_id'), table_name='article_evaluations')
    op.drop_table('article_evaluations')
    # ### end Alembic commands ###
