"""add_user_email_preferences

Revision ID: 1d82db8c546a
Revises: fdf6c488eb9d
Create Date: 2026-04-26 23:32:51.550817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d82db8c546a'
down_revision: Union[str, Sequence[str], None] = 'fdf6c488eb9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'send_at_08h')
    op.drop_column('email_config', 'send_at_16h')
    op.drop_column('email_config', 'recipient_emails')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('receive_email_08h', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('receive_email_16h', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'receive_email_16h')
    op.drop_column('users', 'receive_email_08h')
    op.drop_column('users', 'email')
    op.add_column('email_config', sa.Column('recipient_emails', mysql.TEXT(), nullable=True))
    op.add_column('email_config', sa.Column('send_at_16h', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('email_config', sa.Column('send_at_08h', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
