"""add_is_excluded_to_article_identity

Revision ID: 221b1810379b
Revises: a1a1689350f3
Create Date: 2026-05-22 22:54:59.025667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221b1810379b'
down_revision: Union[str, Sequence[str], None] = 'a1a1689350f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_identity', sa.Column('is_excluded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_identity', 'is_excluded')
    # ### end Alembic commands ###
