"""advanced_email_scheduler

Revision ID: 2680f56377bb
Revises: 1d82db8c546a
Create Date: 2026-04-27 00:12:38.110666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2680f56377bb'
down_revision: Union[str, Sequence[str], None] = '1d82db8c546a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('report_schedule_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('report_schedule_time', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('report_schedule_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('report_filter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_alerts', ['report_filter_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'receive_email_08h')
    op.drop_column('users', 'receive_email_16h')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('receive_email_16h', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('receive_email_08h', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'report_filter_id')
    op.drop_column('users', 'report_schedule_day')
    op.drop_column('users', 'report_schedule_time')
    op.drop_column('users', 'report_schedule_type')
    # ### end Alembic commands ###
