"""add llm_normalized_title to article_details

Revision ID: 77f5cfd3440d
Revises: 221b1810379b
Create Date: 2026-05-23 22:40:11.640401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f5cfd3440d'
down_revision: Union[str, Sequence[str], None] = '221b1810379b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_details', sa.Column('llm_normalized_title', sa.Unicode(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_details', 'llm_normalized_title')
    # ### end Alembic commands ###
