"""Add user auth and seed accounts

Revision ID: 886034eecafa
Revises: a1b2c3d4e5f6
Create Date: 2026-04-06 16:07:55.217778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '886034eecafa'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('rss_sources', 'url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=767),
               existing_nullable=False)
    
    # --- Custom Seed Data ---
    from datetime import datetime
    users_table = sa.table('users',
        sa.column('username', sa.String),
        sa.column('hashed_password', sa.String),
        sa.column('role', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('failed_login_attempts', sa.Integer),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime)
    )
    
    op.bulk_insert(users_table, [
        {
            "username": "epi_scout_admin",
            "hashed_password": "$2b$12$PAyqu7dajQZ.OXhDVFAmGOaw/oSnxUUB/eBUNE4Ybx6o7EKu5.m8G6",
            "role": "admin",
            "is_active": True,
            "failed_login_attempts": 0,
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        },
        {
            "username": "epi_scout_user",
            "hashed_password": "$2b$12$PAyqu7dajQZ.OXhDVFAmGOaw/oSnxUUB/eBUNE4Ybx6o7EKu5.m8G6",
            "role": "user",
            "is_active": True,
            "failed_login_attempts": 0,
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE username IN ('epi_scout_admin', 'epi_scout_user')")
    op.alter_column('rss_sources', 'url',
               existing_type=sa.String(length=767),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
