"""add_scan_stats_to_scheduler_config

Revision ID: a1a1689350f3
Revises: f1a2b3c4d5e6
Create Date: 2026-05-22 17:03:51.415608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a1689350f3'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_config', sa.Column('last_scan_total_checked', sa.Integer(), nullable=True))
    op.add_column('scheduler_config', sa.Column('last_scan_noise_count', sa.Integer(), nullable=True))
    op.add_column('scheduler_config', sa.Column('last_scan_irrelevant_count', sa.Integer(), nullable=True))
    op.add_column('scheduler_config', sa.Column('last_scan_unsure_count', sa.Integer(), nullable=True))
    op.add_column('scheduler_config', sa.Column('last_scan_started_at', sa.DateTime(), nullable=True))
    op.add_column('scheduler_config', sa.Column('last_scan_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_config', 'last_scan_duration_seconds')
    op.drop_column('scheduler_config', 'last_scan_started_at')
    op.drop_column('scheduler_config', 'last_scan_unsure_count')
    op.drop_column('scheduler_config', 'last_scan_irrelevant_count')
    op.drop_column('scheduler_config', 'last_scan_noise_count')
    op.drop_column('scheduler_config', 'last_scan_total_checked')
    # ### end Alembic commands ###
