"""add user_bookmarks

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-18 15:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6g7'
down_revision: Union[str, None] = '886034eecafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article_identity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bookmarks_article_id'), 'user_bookmarks', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_created_at'), 'user_bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_id'), 'user_bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_user_id'), 'user_bookmarks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bookmarks_user_id'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_id'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_created_at'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_article_id'), table_name='user_bookmarks')
    op.drop_table('user_bookmarks')
    # ### end Alembic commands ###
