"""add_scan_status_fields

Revision ID: dce66759a153
Revises: 2680f56377bb
Create Date: 2026-04-27 09:51:46.505303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce66759a153'
down_revision: Union[str, Sequence[str], None] = '2680f56377bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_config', sa.Column('is_scanning', sa.Boolean(), nullable=True))
    op.add_column('scheduler_config', sa.Column('last_scan_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_config', 'last_scan_duration')
    op.drop_column('scheduler_config', 'is_scanning')
    # ### end Alembic commands ###
